<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.0050" tests="8" failures="1">
  <testsuite name="" timestamp="2022-12-31T03:54:50" tests="0" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Root Suite.files" timestamp="2022-12-31T03:54:50" tests="0" file="/home/robert/code/Yatt/demo-yatt-pipe-github-action/test.js" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Root Suite.files.export" timestamp="2022-12-31T03:54:50" tests="4" file="/home/robert/code/Yatt/demo-yatt-pipe-github-action/test.js" time="0.0030" failures="1">
    <testcase name="should export pdf" time="0.0010" classname="files.export">
    </testcase>
    <testcase name="should export html" time="0.0000" classname="files.export">
    </testcase>
    <testcase name="should export yml" time="0.0000" classname="files.export">
    </testcase>
    <testcase name="should export text" time="0.0000" classname="files.export">
      <failure message="An exception occurred" type="Error"><![CDATA[Error: An exception occurred
    at Context.<anonymous> (test.js:20:23)
    at processImmediate (node:internal/timers:466:21)]]></failure>
    </testcase>
  </testsuite>
  <testsuite name="Root Suite.files.import" timestamp="2022-12-31T03:54:50" tests="4" file="/home/robert/code/Yatt/demo-yatt-pipe-github-action/test.js" time="0.0010" failures="0">
    <testcase name="should import pdf" time="0.0000" classname="files.import">
    </testcase>
    <testcase name="should import html" time="0.0000" classname="files.import">
    </testcase>
    <testcase name="should import yml" time="0.0000" classname="files.import">
    </testcase>
    <testcase name="should import text" time="0.0000" classname="files.import">
    </testcase>
  </testsuite>
</testsuites>